Repository DIT112-V21/group-05, pull requests merged in 2021-05, with the labels that each got.

#46 Camera feature WIP
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/res/layout-land/activity_control_car.xml
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
Labels: sprint #3 stories

#47 Login/register pages
  android/androidappcar/app/build.gradle
  android/androidappcar/app/google-services.json
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/LoginActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/MainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/TestActivity.java
  android/androidappcar/app/src/main/res/layout/activity_login.xml
  android/androidappcar/app/src/main/res/layout/activity_main.xml
  android/androidappcar/app/src/main/res/layout/activity_register.xml
  android/androidappcar/app/src/main/res/layout/activity_test.xml
  android/androidappcar/build.gradle
Labels: sprint #3 stories

#48 Finished Camera changes
  arduino/smartcar/smartcar.ino
Labels: sprint #3 stories

#49 Delivery System
  android/.idea/modules.xml
  android/.idea/workspace.xml
  android/androidappcar/.idea/compiler.xml
  android/androidappcar/.idea/gradle.xml
  android/androidappcar/.idea/misc.xml
  android/androidappcar/app/build.gradle
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/Delivery.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryListAdapter.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/MainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterDeliveryActivity.java
  android/androidappcar/app/src/main/res/layout/activity_main.xml
  android/androidappcar/app/src/main/res/layout/activity_register_delivery.xml
  android/androidappcar/app/src/main/res/layout/delivery_card.xml
  android/androidappcar/app/src/main/res/layout/delivery_main.xml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
Labels: sprint #3 stories

#51 Removed speedLimiter() method
  arduino/smartcar/smartcar.ino
Labels: sprint #3 stories

#55 Fixed Bugs & made updates related to speed meter
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/res/drawable-v24/angleturnleft.png
  android/androidappcar/app/src/main/res/drawable-v24/speedometer.png
  android/androidappcar/app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  android/androidappcar/app/src/main/res/drawable/ic_baseline_arrow_forward_24.xml
  android/androidappcar/app/src/main/res/drawable/ic_baseline_speed.xml
  android/androidappcar/app/src/main/res/drawable/ic_baseline_speed_24.xml
  android/androidappcar/app/src/main/res/drawable/turnangleright.png
  android/androidappcar/app/src/main/res/layout-land/activity_control_car.xml
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
Labels: sprint #3 stories

#57 Implemented speed limit editor
  android/androidappcar/.idea/compiler.xml
  android/androidappcar/.idea/misc.xml
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/MainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/SpeedLimit.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/StaffMainActivity.java
  android/androidappcar/app/src/main/res/drawable/ic_search_black_24dp.xml
  android/androidappcar/app/src/main/res/layout/activity_staff_main.xml
  android/androidappcar/app/src/main/res/layout/speed_limit_window.xml
  android/androidappcar/app/src/main/res/menu/drawer_menu_staff.xml
  android/androidappcar/app/src/main/res/values/styles.xml
  android/androidappcar/build.gradle
Labels: sprint #4 stories

#58 Implemented power on and power off buttons
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
Labels: enhancement

#63 Removed home pages for staff and patients and got rid of unused code
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveriesActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/LoginActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/MainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/PatientMainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterDeliveryActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/StaffMainActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/TestActivity.java
  android/androidappcar/app/src/main/res/layout/activity_deliveries.xml
  android/androidappcar/app/src/main/res/layout/activity_main.xml
  android/androidappcar/app/src/main/res/layout/activity_patient_main.xml
  android/androidappcar/app/src/main/res/layout/activity_staff_main.xml
  android/androidappcar/app/src/main/res/layout/activity_test.xml
  android/androidappcar/app/src/main/res/menu/drawer_menu_patient.xml
  android/androidappcar/app/src/main/res/menu/drawer_menu_staff.xml
Labels: sprint #4 stories

#64 Added green/red light and button for speed limit, fixed bug in landscape
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterDeliveryActivity.java
  android/androidappcar/app/src/main/res/drawable-v24/speedometer.png
  android/androidappcar/app/src/main/res/drawable/car_off.png
  android/androidappcar/app/src/main/res/drawable/car_on.png
  android/androidappcar/app/src/main/res/layout-land/activity_control_car.xml
  android/androidappcar/app/src/main/res/layout-land/speed_limit_window.xml
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
  android/androidappcar/app/src/main/res/menu/drawer_menu_staff.xml
Labels: bug, enhancement

#66 Added a button for mqtt editing
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/Connectivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/res/drawable/connection_icon.png
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
  android/androidappcar/app/src/main/res/layout/connectivity_window.xml
Labels: enhancement

#67 edited topic for the mqtt on the car
  arduino/smartcar/smartcar.ino
Labels: bug

#68 Removed connectivity button and fixed speed display
  android/androidappcar/app/src/main/AndroidManifest.xml
  android/androidappcar/app/src/main/java/com/example/androidappcar/Connectivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/res/layout/activity_control_car.xml
  android/androidappcar/app/src/main/res/layout/connectivity_window.xml
Labels: bug

#72 README.md updated to have better structure
  README.md
Labels: documentation, sprint #4 stories

#73 deleted some unnecessary changes
  README.md
Labels: documentation

#75 added missing text to readme.md
  README.md
Labels: documentation, sprint #4 stories

#76 Removed unused code and made improvements to driving commands
  android/androidappcar/app/src/main/java/com/example/androidappcar/ControlCarActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/Delivery.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryActivityStaff.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/DeliveryListAdapter.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/LoginActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/MqttClient.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/RegisterDeliveryActivity.java
  android/androidappcar/app/src/main/java/com/example/androidappcar/confirmedList.java
Labels: enhancement

#77 added resources and made changes to readme.md
  README.md
Labels: documentation

#79 finalizing the readme.md file
  README.md
Labels: documentation, sprint #4 stories
